apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fraudguard-kafka
  namespace: fraudguard
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 24
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transactions-raw
  namespace: fraudguard
  labels:
    strimzi.io/cluster: fraudguard-kafka
spec:
  partitions: 12
  replicas: 3
  config:
    retention.ms: "86400000"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fraud-alerts
  namespace: fraudguard
  labels:
    strimzi.io/cluster: fraudguard-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: "2592000000"
