version: "3.9"
services:
  # Service applicatif Node.js
  web:
    build: .
    ports:
      - "8080:8080" # Mapper le port 8080 local vers le port 8080 du conteneur
    environment:
      - APP_ENV=development
      - DB_HOST=db # Nom du service PostgreSQL (resolution DNS automatique par Docker)
      - DB_PORT=5432
      - DB_NAME=ynov_db
      - DB_USER=ynov
      - DB_PASSWORD=secret_password
      - REDIS_HOST=cache # Nom du service cache
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy # Attendre que le healthcheck PostgreSQL soit healthy
      cache:
        condition: service_healthy # Attendre que le healthcheck Redis soit healthy
    networks:
      - app-network



  # Service PostgreSQL
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=ynov_db
      - POSTGRES_USER=ynov
      - POSTGRES_PASSWORD=secret_password
    volumes:
      # Volume nomme pour la persistance des donnees
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ynov -d ynov_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  cache:
    image: redis:7-alpine # Utiliser la version 7
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app-network

# Definition des volumes nommes
volumes:
  db_data:

# Definition du reseau dedie
networks:
  app-network:
    driver: bridge