apiVersion: v1
kind: Secret
metadata:
  name: logistream-secrets
  namespace: logistream
type: Opaque
stringData:
  # stringData : Kubernetes encode automatiquement en base64
  DB_URL: "postgresql://logistream:motdepasse@cloud-sql-proxy:5432/logistream_prod"
  MAPS_API_KEY: "AIza-demo-logistream-maps-key-tp3"
  JWT_SECRET: "logistream-jwt-secret-2026-production"